Adding bazel build/test workflow

diff --git a/.github/workflows/java-tutorial-bazel.yaml b/.github/workflows/java-tutorial-bazel.yaml
--- a/.github/workflows/java-tutorial-bazel.yaml
+++ b/.github/workflows/java-tutorial-bazel.yaml
@@ -9,26 +9,31 @@ jobs:
 
     steps:
       - uses: actions/checkout@v1
-
+      - uses: bazelbuild/setup-bazelisk@v2
       - name: Mount bazel cache
-        uses: actions/cache@v1
+        uses: actions/cache@v3
         with:
-          path: "/home/runner/.cache/bazel"
-          key: bazel
-
-      - name: Install bazelisk
-        run: |
-          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
-          mkdir -p "${GITHUB_WORKSPACE}/bin/"
-          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
-          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
+          path: "~/.cache/bazel"
+          key: Gradle-Bazel-Example-Repo
       - name: Change Directory
-        run: |
-          cd java-tutorial
+        run: cd java-tutorial
       - name: Test
         run: |
-          "${GITHUB_WORKSPACE}/bin/bazel" test //...
+          bazel test //...
+          TEST_RES=$?
+          set -e
 
+          # Return codes for commands bazel build, bazel test:
+          # 1 - Build failed.
+          # 3 - Build OK, but some tests failed or timed out.
+          # 4 - Build successful but no tests were found even though testing was requested.
+
+          if [ ! $TEST_RES -eq 4 ] && [ ! $TEST_RES -eq 0 ]
+          then
+            echo 'Tests failed.'
+            exit 1
+          else
+            echo 'Tests succeeded or no tests were found.'
+          fi
       - name: Build
-        run: |
-          "${GITHUB_WORKSPACE}/bin/bazel" build //...
+        run: bazel build //...
